BugRay/Models/BugViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BugRay.Models
{
    public class BugViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte BugStatus { get; set; }
        public string Comments { get; set; }
    }
}

BugRay/Models/DashboardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BugRay.Models
{
    public class DashboardViewModel
    {
        public List<BugViewModel> Issues { get; set; }
    }
}

BugRay/Models/DataModels/BugModel.cs
using System.ComponentModel.DataAnnotations;

namespace BugRay.Models.DataModels
{
    public class BugModel
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte BugStatus { get; set; }
        public string Comments { get; set; }

    }
}

BugRay/Models/ErrorViewModel.cs
using System;

namespace BugRay.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BugRay/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using BugRay.Data;
using BugRay.Models;
using Microsoft.AspNetCore.Mvc;
using BugRay.Models.DataModels;
using System.Text;
using BugRay.Utility;

namespace BugRay.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IMapper _mapper;

        /// <summary>
        /// Application DB context object to acess the DB.
        /// </summary>
        ApplicationDbContext _context;

        /// <summary>
        /// Ctor to provide the inital instansiation.
        /// </summary>
        /// <param name="db"></param>
        public DashboardController(ApplicationDbContext db, IMapper mapper)
        {
            _context = db;
            _mapper = mapper;
        }

        /// <summary>
        /// As DB contect is an imprtant parameter so to prevent misuse dispose it as soon as execution is complete.
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }


        /// <summary>
        /// Action method for Dashboard page.
        /// </summary>
        /// <returns>
        /// View
        /// </returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Action method to save the data of the Bug added.
        /// </summary>
        /// <param name="bug">
        /// Obejct containg the inserted bug data
        /// </param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult SaveIssue(BugViewModel bugViewModel)
        {
            StringBuilder stringMessage = new StringBuilder();
            OperationObject operation = new OperationObject();

            var bug = _mapper.Map<BugViewModel, BugModel>(bugViewModel);
            _context.Bugs.Add(bug);

            try
            {
                _context.SaveChanges();
                stringMessage.Append("Data Saved");
                operation.OperationValue = true;
            }
            catch (Exception e)
            {
                stringMessage.Append("Data not Saved due to " + e.Message);
                operation.OperationValue = false;
            }

            operation.Message = stringMessage.ToString();

            return Json(operation);
        }

        public List<BugModel> GetAllIssuesData()
        {
            return _context.Bugs.ToList(); ;
        }

        public IActionResult GetAllIssues()
        {
            StringBuilder stringMessage = new StringBuilder();
            DashboardViewModel model = new DashboardViewModel();
            model.Issues = _mapper.Map<List<BugViewModel>>(GetAllIssuesData());

            return PartialView("_AllIssuesForDashboard", model);
        }

        public IActionResult DeleteIssue(int id)
        {
            StringBuilder stringMessage = new StringBuilder();
            OperationObject operation = new OperationObject();
            try
            {
                BugModel bug = new BugModel();
                bug.Id = id;
                _context.Bugs.Remove(bug);
                _context.SaveChanges();
                operation.OperationValue = true;
                stringMessage.Append("Issue is Deleted");
            }
            catch (Exception e)
            {
                operation.OperationValue = false;
                stringMessage.Append(e);
            }

            operation.Message = stringMessage.ToString();

            return Json(operation);
        }

    }
}

BugRay/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BugRay.Models;

namespace BugRay.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BugRay/Views/Dashboard/Index.cshtml
@model BugRay.Models.BugViewModel
<div class="container">
    <h1>Add a Issue</h1>
    <div class="jumbotron">
        <form method="post" id="bugForm" enctype="multipart/form-data">
            <div>
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Description"></label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <label asp-for="Comments"></label>
                    <textarea asp-for="Comments" class="form-control"></textarea>
                </div>
            </div>
            <input type="button" class="btn btn-primary" value="Save" onclick="saveForm()">
        </form>
    </div>
    <div id="issueDiv">

    </div>
</div>
<script src="~/js/dashboard.js"></script>

BugRay/Views/Dashboard/_AllIssuesForDashboard.cshtml
@model BugRay.Models.DashboardViewModel


@foreach (var issue in Model.Issues)
{
    <div class="card" id="cardId_@issue.Id">
        <div class="card-header">
            <div class="row">
                <div class="col-11">
                    <p data-toggle="collapse" data-target="#issueBox_@issue.Id">@issue.Name</p>
                </div>
                <div class="col-1">
                    <i class="fa fa-minus-square fa-3x" style="color:red" id="deleteBtn_@issue.Id" onclick="deleteIssue(this)">
                    </i>
                </div>
            </div>
        </div>
        <div id="issueBox_@issue.Id" class="card-body collapse">
            <ul>
                <li>@issue.Description</li>
                <li>@issue.BugStatus</li>
                <li>@issue.Comments</li>
            </ul>
        </div>
    </div>
}

BugRay/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BugRay/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BugRay</title>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <partial name="_NavBar" />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BugRay - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/bootbox.js/bootbox.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BugRay/Views/Shared/_NavBar.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BugRay</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial" />
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>